t = ('Athletico Paranaense', 'Atlético Mineiro Saf', 'Bahia', 'Botafogo', 'Chapecoense', 'Corinthians', 'Coritiba S.a.f.', 'Cruzeiro Saf', 'Flamengo', 'Fluminense', 'Grêmio', 'Internacional', 'Mirassol', 'Palmeiras', 'Red Bull Bragantino', 'Remo', 'Santos Fc', 'São Paulo', 'Vasco da Gama Saf', 'Vitória')
print ('5 primeiros colocados')
print (t[0:5])
print ('--------------------------------------------------')
print ('4 últimos colocados')
print (t[16:])
print ('--------------------------------------------------')
print('Ordem alfabética')
print (sorted(t))
print ('--------------------------------------------------')
print (f'Posição da Chapecoense {t.index('Chapecoense')+1} colocado')